# https://raw.githubusercontent.com/ElementRef/AboutConfig/main/filter/element.ref.global.customs.ini
HOST-SUFFIX,2nvx.com
HOST-SUFFIX,adonismale.com
HOST-SUFFIX,charliemonroe.net
HOST-SUFFIX,cnbeta.com
HOST-SUFFIX,ghcr.io
HOST-SUFFIX,ifixit.com
HOST-SUFFIX,itdmusics.com
HOST-SUFFIX,itdmusics.in
HOST-SUFFIX,kelee.one
HOST-SUFFIX,notion.com
HOST-SUFFIX,notion.site
HOST-SUFFIX,notion.so
HOST-SUFFIX,notionusercontent.com
HOST-SUFFIX,ouo.io
HOST-SUFFIX,out.com
HOST-SUFFIX,pincong.rocks
HOST-SUFFIX,pulsar.gg
HOST-SUFFIX,signal65.com
HOST-SUFFIX,sotwe.com
HOST-SUFFIX,surge.sh
HOST-SUFFIX,teoh.io
HOST-SUFFIX,v2ex.com
HOST,forum.bambulab.com
HOST,gateway-us.umami.dev
HOST,is1-ssl.mzstatic.com
HOST,is1.mzstatic.com
HOST,is2-ssl.mzstatic.com
HOST,is2.mzstatic.com
HOST,is3-ssl.mzstatic.com
HOST,is3.mzstatic.com
HOST,is4-ssl.mzstatic.com
HOST,is4.mzstatic.com
HOST,is5-ssl.mzstatic.com
HOST,is5.mzstatic.com
HOST,lastfm-img.freetls.fastly.net
HOST,pi-from-scratch.vercel.app
HOST,storage.googleapis.com
HOST,unavatar.now.sh
HOST,unavatar.vercel.app
# https://x.com/rxliuli/status/2050115144618049742
HOST,apps.apple.com
# https://x.com/unixzii/status/2050061378615124305
HOST-SUFFIX,push.apple.com
# https://kelee.one/Tool/Loon/Lpx
DOMAIN-SUFFIX,astrill.com
DOMAIN-SUFFIX,astrill.org
DOMAIN-SUFFIX,browserleaks.com
DOMAIN-SUFFIX,browserleaks.org
DOMAIN-SUFFIX,dnsleak.asn247.net
DOMAIN-SUFFIX,dnsleak.com
DOMAIN-SUFFIX,dnsleaktest.com
DOMAIN-SUFFIX,expressvpn.com
DOMAIN-SUFFIX,ipapi.co
DOMAIN-SUFFIX,ipleak.net
DOMAIN-SUFFIX,nordvpn.com
DOMAIN-SUFFIX,perfect-privacy.com
DOMAIN-SUFFIX,pixelscan.net
DOMAIN-SUFFIX,surfshark.com
DOMAIN-SUFFIX,surfshark.com
DOMAIN-SUFFIX,surfsharkdns.com
DOMAIN-SUFFIX,vpnunlimited.com
DOMAIN-SUFFIX,whoer.net
DOMAIN-SUFFIX,whrq.net
DOMAIN,ip-scan.adspower.net
DOMAIN,ipv4.ping0.cc
DOMAIN,ipv6.ping0.cc
