# 2026/6/15 10:22:47 https://raw.githubusercontent.com/ElementRef/AboutConfig/main/filter/element.ref.apples.mixture.ini
HOST,api.smoot.apple.cn
HOST,appleintelligencefeedback.care.apple.com
HOST-SUFFIX,a1.mzstatic.com
HOST-SUFFIX,a2.mzstatic.com
HOST-SUFFIX,a3.mzstatic.com
HOST-SUFFIX,a4.mzstatic.com
HOST-SUFFIX,a5.mzstatic.com
HOST-SUFFIX,aaplimg.com
HOST-SUFFIX,adcdownload.apple.com.akadns.net
HOST-SUFFIX,amp-api.media.apple.com
HOST-SUFFIX,appldnld.g.aaplimg.com
HOST-SUFFIX,apple-cloudkit.com
HOST-SUFFIX,apple-dns.net
HOST-SUFFIX,apple-mapkit.com
HOST-SUFFIX,apple.co
HOST-SUFFIX,apple.com
HOST-SUFFIX,apple.com.cn
HOST-SUFFIX,apple.com.edgekey.net.globalredir.akadns.net
HOST-SUFFIX,apple.news
HOST-SUFFIX,apps.mzstatic.com
HOST-SUFFIX,appsto.re
HOST-SUFFIX,appstore.com
HOST-SUFFIX,cdn-apple.com
HOST-SUFFIX,cds-cdn.v.aaplimg.com
HOST-SUFFIX,cds.apple.com.akadns.net
HOST-SUFFIX,cl1-cdn.origin-apple.com.akadns.net
HOST-SUFFIX,cl3-cdn.origin-apple.com.akadns.net
HOST-SUFFIX,cl4-cdn.origin-apple.com.akadns.net
HOST-SUFFIX,cl5-cdn.origin-apple.com.akadns.net
HOST-SUFFIX,clientflow.apple.com.akadns.net
HOST-SUFFIX,cn-ssl.ls.apple.com
HOST-SUFFIX,cn.ls.apple.com
HOST-SUFFIX,configuration.apple.com.akadns.net
HOST-SUFFIX,dd-cdn.origin-apple.com.akadns.net
HOST-SUFFIX,download.developer.apple.com
HOST-SUFFIX,gsp10-ssl-cn.ls.apple.com
HOST-SUFFIX,gsp11-cn.ls.apple.com
HOST-SUFFIX,gsp12-cn.ls.apple.com
HOST-SUFFIX,gsp13-cn.ls.apple.com
HOST-SUFFIX,gsp4-cn.ls.apple.com
HOST-SUFFIX,gsp4-cn.ls.apple.com.edgekey.net.globalredir.akadns.net
HOST-SUFFIX,gsp5-cn.ls.apple.com
HOST-SUFFIX,gsp85-cn-ssl.ls.apple.com
HOST-SUFFIX,gspe19-2-cn-ssl.ls-apple.com.akadns.net
HOST-SUFFIX,gspe19-2-cn-ssl.ls.apple.com
HOST-SUFFIX,gspe19-cn-ssl.ls.apple.com
HOST-SUFFIX,gspe19-cn.ls-apple.com.akadns.net
HOST-SUFFIX,gspe19-cn.ls.apple.com
HOST-SUFFIX,gspe21-ssl.ls.apple.com
HOST-SUFFIX,gspe35-ssl.ls.apple.com
HOST-SUFFIX,gspe79-cn-ssl.ls.apple.com
HOST-SUFFIX,guzzoni-apple-com.v.aaplimg.com
HOST-SUFFIX,guzzoni.smoot.apple.com
HOST-SUFFIX,icloud-content.com
HOST-SUFFIX,icloud.com
HOST-SUFFIX,icloud.com.cn
HOST-SUFFIX,init-p01st.push.apple.com
HOST-SUFFIX,init-s01st.push.apple.com
HOST-SUFFIX,init.ess.apple.com
HOST-SUFFIX,iosapps.itunes.g.aaplimg.com
HOST-SUFFIX,iphone-ld.origin-apple.com.akadns.net
HOST-SUFFIX,is1-ssl.mzstatic.com
HOST-SUFFIX,is1.mzstatic.com
HOST-SUFFIX,is2-ssl.mzstatic.com
HOST-SUFFIX,is2.mzstatic.com
HOST-SUFFIX,is3-ssl.mzstatic.com
HOST-SUFFIX,is3.mzstatic.com
HOST-SUFFIX,is4-ssl.mzstatic.com
HOST-SUFFIX,is4.mzstatic.com
HOST-SUFFIX,is5-ssl.mzstatic.com
HOST-SUFFIX,is5.mzstatic.com
HOST-SUFFIX,itunes-apple.com.akadns.net
HOST-SUFFIX,itunes.com
HOST-SUFFIX,me.com
HOST-SUFFIX,mesu-cdn.apple.com.akadns.net
HOST-SUFFIX,mesu-china.apple.com.akadns.net
HOST-SUFFIX,organicfruitapps.com
HOST-SUFFIX,oscdn.origin-apple.com.akadns.net
HOST-SUFFIX,osxapps.itunes.g.aaplimg.com
HOST-SUFFIX,probe.siri.apple.com
HOST-SUFFIX,prod-support.apple-support.akadns.net
HOST-SUFFIX,push-apple.com.akadns.net
HOST-SUFFIX,s.mzstatic.com
HOST-SUFFIX,seed-sequoia.siri.apple.com
HOST-SUFFIX,seed-swallow.siri.apple.com
HOST-SUFFIX,seed.siri.apple.com
HOST-SUFFIX,static.gc.apple.com
HOST-SUFFIX,stocks-sparkline-lb.apple.com.akadns.net
HOST-SUFFIX,store.apple.com.edgekey.net
HOST-SUFFIX,store.storeimages.apple.com.akadns.net
HOST-SUFFIX,store.storeimages.cdn-apple.com
HOST-SUFFIX,support-china.apple-support.akadns.net
HOST-SUFFIX,swallow-apple-com.v.aaplimg.com
HOST-SUFFIX,swcatalog-cdn.apple.com.akadns.net
HOST-SUFFIX,swcdn.g.aaplimg.com
HOST-SUFFIX,swdist.apple.com.akadns.net
HOST-SUFFIX,swscan-cdn.apple.com.akadns.net
HOST-SUFFIX,updates-http.cdn-apple.com.akadns.net
HOST-SUFFIX,valid.origin-apple.com.akadns.net
HOST-SUFFIX,weather-data.apple.com.akadns.net
IP-CIDR,139.178.128.0/18,no-resolve
IP-CIDR,144.178.0.0/19,no-resolve
IP-CIDR,144.178.36.0/22,no-resolve
IP-CIDR,144.178.48.0/20,no-resolve
IP-CIDR,17.0.0.0/8,no-resolve
IP-CIDR,192.35.50.0/24,no-resolve
IP-CIDR,198.183.17.0/24,no-resolve
IP-CIDR,205.180.175.0/24,no-resolve
IP-CIDR,63.92.224.0/19,no-resolve
IP-CIDR,65.199.22.0/23,no-resolve
PROCESS-NAME,CoreLocationAgent
PROCESS-NAME,WeatherWidget
PROCESS-NAME,apsd
PROCESS-NAME,com.apple.Maps
PROCESS-NAME,com.apple.geod
PROCESS-NAME,findmydevice-user-agent
PROCESS-NAME,fmfd
PROCESS-NAME,mapspushd
