# 2026/4/7 05:41:33 https://raw.githubusercontent.com/ElementRef/AboutConfig/main/filter/element.ref.global.mixture.ini
HOST,adsbypasser.github.io
HOST,api-glb-sea.smoot.apple.com
HOST,cc-ext-prod-pkgs.s3.amazonaws.com
HOST,cdn.apple-cloudkit.com
HOST,cvws.icloud-content.com
HOST,d1q6f0aelx0por.cloudfront.net
HOST,d36jcksde1wxzq.cloudfront.net
HOST,developer.apple.com
HOST,devimages-cdn.apple.com
HOST,devstreaming-cdn.apple.com
HOST,e122475.dscg.akamaiedge.net
HOST,forum.bambulab.com
HOST,gspe1-ssl.ls.apple.com
HOST,is1-ssl.mzstatic.com
HOST,is1.mzstatic.com
HOST,is2-ssl.mzstatic.com
HOST,is2.mzstatic.com
HOST,is3-ssl.mzstatic.com
HOST,is3.mzstatic.com
HOST,is4-ssl.mzstatic.com
HOST,is4.mzstatic.com
HOST,is5-ssl.mzstatic.com
HOST,is5.mzstatic.com
HOST,itunes.apple.com
HOST,js-cdn.music.apple.com
HOST,licdn.cn.cdn20.com
HOST,linkedin.sc.omtrdc.net
HOST,lookup-api.apple.com
HOST,mask-api.icloud.com
HOST,mask-h2.icloud.com
HOST,mask.icloud.com
HOST,news-assets.apple.com
HOST,news-client.apple.com
HOST,news-edge.apple.com
HOST,officecdn-microsoft-com.akamaized.net
HOST,storage.googleapis.com
HOST,testflight.apple.com
HOST,tv.applemusic.com
HOST,unavatar.now.sh
HOST,unavatar.vercel.app
HOST-KEYWORD,1drv
HOST-KEYWORD,adobe
HOST-KEYWORD,hotmail
HOST-KEYWORD,instagram
HOST-KEYWORD,microsoft
HOST-SUFFIX,10xfotolia.com
HOST-SUFFIX,1drv.com
HOST-SUFFIX,2nvx.com
HOST-SUFFIX,aadrm.com
HOST-SUFFIX,acompli.com
HOST-SUFFIX,acompli.net
HOST-SUFFIX,acrobat.com
HOST-SUFFIX,adobe-aemassets-value.com
HOST-SUFFIX,adobe-audience-finder.com
HOST-SUFFIX,adobe-video-partner-finder.com
HOST-SUFFIX,adobe.com
HOST-SUFFIX,adobe.ly
HOST-SUFFIX,adobeaemcloud.com
HOST-SUFFIX,adobeaemcloud.net
HOST-SUFFIX,adobeawards.com
HOST-SUFFIX,adobecc.com
HOST-SUFFIX,adobecce.com
HOST-SUFFIX,adobeccstatic.com
HOST-SUFFIX,adobecontent.io
HOST-SUFFIX,adobecreativityawards.com
HOST-SUFFIX,adobedc.cn
HOST-SUFFIX,adobedc.net
HOST-SUFFIX,adobedemo.com
HOST-SUFFIX,adobedtm.com
HOST-SUFFIX,adobeexchange.com
HOST-SUFFIX,adobeexperienceawards.com
HOST-SUFFIX,adobegov.com
HOST-SUFFIX,adobehiddentreasures.com
HOST-SUFFIX,adobejanus.com
HOST-SUFFIX,adobeku.com
HOST-SUFFIX,adobelanding.com
HOST-SUFFIX,adobelogin.com
HOST-SUFFIX,adobeoobe.com
HOST-SUFFIX,adobeplatinumclub.com
HOST-SUFFIX,adobeprojectm.com
HOST-SUFFIX,adobesc.com
HOST-SUFFIX,adobesign.com
HOST-SUFFIX,adobesigncdn.com
HOST-SUFFIX,adobespark.com
HOST-SUFFIX,adobess.com
HOST-SUFFIX,adobestock.com
HOST-SUFFIX,adobetcstrialdvd.com
HOST-SUFFIX,adobetechcomm.com
HOST-SUFFIX,adobetechcommcallback.com
HOST-SUFFIX,adobetechcommdemo.com
HOST-SUFFIX,adobexdplatform.com
HOST-SUFFIX,adonismale.com
HOST-SUFFIX,aka.ms
HOST-SUFFIX,appcenter.ms
HOST-SUFFIX,apple-dns.net
HOST-SUFFIX,apple.news
HOST-SUFFIX,apps.apple.com
HOST-SUFFIX,appsto.re
HOST-SUFFIX,aria.ms
HOST-SUFFIX,asp.net
HOST-SUFFIX,aspnetcdn.com
HOST-SUFFIX,assets-yammer.com
HOST-SUFFIX,assetsadobe.com
HOST-SUFFIX,authorxml.com
HOST-SUFFIX,azure.com
HOST-SUFFIX,azure.net
HOST-SUFFIX,azureedge.net
HOST-SUFFIX,azurerms.com
HOST-SUFFIX,behance.net
HOST-SUFFIX,bing.com
HOST-SUFFIX,blobstore.apple.com
HOST-SUFFIX,bluefootcms.com
HOST-SUFFIX,businesscatalyst.com
HOST-SUFFIX,ccnsite.com
HOST-SUFFIX,ccpsx.com
HOST-SUFFIX,cdn-apple.com
HOST-SUFFIX,cdninstagram.com
HOST-SUFFIX,charliemonroe.net
HOST-SUFFIX,cloudapp.net
HOST-SUFFIX,cloudappsecurity.com
HOST-SUFFIX,compose-spec.io
HOST-SUFFIX,compresspdf.new
HOST-SUFFIX,cotolia.com
HOST-SUFFIX,creativecloud.com
HOST-SUFFIX,creativesdk.com
HOST-SUFFIX,developria.com
HOST-SUFFIX,digicert.com
HOST-SUFFIX,docker.com
HOST-SUFFIX,docker.io
HOST-SUFFIX,dockerhub.com
HOST-SUFFIX,docs.com
HOST-SUFFIX,dollarfotoclub.com
HOST-SUFFIX,dollarphotoclub.com
HOST-SUFFIX,dollarphotosclub.com
HOST-SUFFIX,douwriteright.com
HOST-SUFFIX,echocdn.com
HOST-SUFFIX,echosign.com
HOST-SUFFIX,edgefonts.net
HOST-SUFFIX,enablementadobe.com
HOST-SUFFIX,ffotolia.com
HOST-SUFFIX,fiotolia.com
HOST-SUFFIX,foftolia.com
HOST-SUFFIX,fonolia.com
HOST-SUFFIX,fotiolia.com
HOST-SUFFIX,fotoiia.com
HOST-SUFFIX,fotolia-noticias.com
HOST-SUFFIX,fotolia.cc
HOST-SUFFIX,fotolia.com
HOST-SUFFIX,fotolia.tv
HOST-SUFFIX,fotolja.com
HOST-SUFFIX,fptolia.com
HOST-SUFFIX,ftcdn.net
HOST-SUFFIX,geotrust.com
HOST-SUFFIX,gfotolia.com
HOST-SUFFIX,gfx.ms
HOST-SUFFIX,ghcr.io
HOST-SUFFIX,globalsign.com
HOST-SUFFIX,godaddy.com
HOST-SUFFIX,gostorego.com
HOST-SUFFIX,hotmail.com
HOST-SUFFIX,imagineecommerce.com
HOST-SUFFIX,instagr.am
HOST-SUFFIX,instagram.com
HOST-SUFFIX,itdmusics.com
HOST-SUFFIX,itdmusics.in
HOST-SUFFIX,kelee.one
HOST-SUFFIX,l-0005.dc-msedge.net
HOST-SUFFIX,l-0005.l-msedge.net
HOST-SUFFIX,licdn.cn
HOST-SUFFIX,licdn.com
HOST-SUFFIX,linkedin.at
HOST-SUFFIX,linkedin.cn
HOST-SUFFIX,linkedin.com
HOST-SUFFIX,live.com
HOST-SUFFIX,live.net
HOST-SUFFIX,lnkd.in
HOST-SUFFIX,lync.com
HOST-SUFFIX,macromedia.com
HOST-SUFFIX,mageconf.com
HOST-SUFFIX,mageconf.com.ua
HOST-SUFFIX,magento.com
HOST-SUFFIX,magento.net
HOST-SUFFIX,magentocommerce.com
HOST-SUFFIX,magentoliveconference.com
HOST-SUFFIX,magentomobile.com
HOST-SUFFIX,marketing-cloud.com
HOST-SUFFIX,marketing-nirvana.com
HOST-SUFFIX,marketo.co.uk
HOST-SUFFIX,marketo.tv
HOST-SUFFIX,marketodesigner.com
HOST-SUFFIX,microsoft.com
HOST-SUFFIX,microsoftonline.com
HOST-SUFFIX,mktdns.com
HOST-SUFFIX,mkto-c0100.com
HOST-SUFFIX,mktorest.com
HOST-SUFFIX,mktroute.com
HOST-SUFFIX,mobilemarketo.com
HOST-SUFFIX,motolia.com
HOST-SUFFIX,msappproxy.net
HOST-SUFFIX,msauth.net
HOST-SUFFIX,msauthimages.net
HOST-SUFFIX,msedge.net
HOST-SUFFIX,msft.net
HOST-SUFFIX,msftauth.net
HOST-SUFFIX,msftauthimages.net
HOST-SUFFIX,msftidentity.com
HOST-SUFFIX,msidentity.com
HOST-SUFFIX,msn.com
HOST-SUFFIX,msocdn.com
HOST-SUFFIX,msocsp.com
HOST-SUFFIX,mstea.ms
HOST-SUFFIX,notion.com
HOST-SUFFIX,notion.site
HOST-SUFFIX,notion.so
HOST-SUFFIX,notionusercontent.com
HOST-SUFFIX,o365weve.com
HOST-SUFFIX,oaspapps.com
HOST-SUFFIX,ocsp.apple.com
HOST-SUFFIX,office.com
HOST-SUFFIX,office.net
HOST-SUFFIX,office365.com
HOST-SUFFIX,officeppe.net
HOST-SUFFIX,omniroot.com
HOST-SUFFIX,onedrive.com
HOST-SUFFIX,onenote.com
HOST-SUFFIX,onenote.net
HOST-SUFFIX,onestore.ms
HOST-SUFFIX,ouo.io
HOST-SUFFIX,out.com
HOST-SUFFIX,outlook.com
HOST-SUFFIX,outlookmobile.com
HOST-SUFFIX,pdf.new
HOST-SUFFIX,phonefactor.net
HOST-SUFFIX,photolia.net
HOST-SUFFIX,photoshop.com
HOST-SUFFIX,pincong.rocks
HOST-SUFFIX,placesdocs.com
HOST-SUFFIX,public-trust.com
HOST-SUFFIX,pulsar.gg
HOST-SUFFIX,redd.it
HOST-SUFFIX,reddit.com
HOST-SUFFIX,redditmail.com
HOST-SUFFIX,redditmedia.com
HOST-SUFFIX,redditstatic.com
HOST-SUFFIX,reddituploads.com
HOST-SUFFIX,reddituploads.com.cdn-cf.behance.net
HOST-SUFFIX,reddituploads.com.cdn-cf.dropbox.com
HOST-SUFFIX,revenue-performance-management.com
HOST-SUFFIX,s2stagehance.com
HOST-SUFFIX,scene7.com
HOST-SUFFIX,sfbassets.com
HOST-SUFFIX,sfx.ms
HOST-SUFFIX,sharepoint.com
HOST-SUFFIX,sharepointonline.com
HOST-SUFFIX,sign.new
HOST-SUFFIX,signal65.com
HOST-SUFFIX,skype.com
HOST-SUFFIX,skypeassets.com
HOST-SUFFIX,skypeforbusiness.com
HOST-SUFFIX,staffhub.ms
HOST-SUFFIX,sundanceignite2016.com
HOST-SUFFIX,surge.sh
HOST-SUFFIX,svc.ms
HOST-SUFFIX,sway-cdn.com
HOST-SUFFIX,sway-extensions.com
HOST-SUFFIX,sway.com
HOST-SUFFIX,symantec.com
HOST-SUFFIX,symcb.com
HOST-SUFFIX,symcd.com
HOST-SUFFIX,tenbyfotolia.com
HOST-SUFFIX,teoh.io
HOST-SUFFIX,thawte.com
HOST-SUFFIX,toutapp.com
HOST-SUFFIX,trafficmanager.net
HOST-SUFFIX,tv.apple.com
HOST-SUFFIX,typekit.com
HOST-SUFFIX,typekit.net
HOST-SUFFIX,uservoice.com
HOST-SUFFIX,v2ex.com
HOST-SUFFIX,verisign.com
HOST-SUFFIX,virtualearth.net
HOST-SUFFIX,visualstudio.com
HOST-SUFFIX,votolia.com
HOST-SUFFIX,windows-ppe.net
HOST-SUFFIX,windows.com
HOST-SUFFIX,windows.net
HOST-SUFFIX,windowsazure.com
HOST-SUFFIX,windowsupdate.com
HOST-SUFFIX,worldsecureemail.com
HOST-SUFFIX,worldsecuresystems.com
HOST-SUFFIX,wunderlist.com
HOST-SUFFIX,xbox.com
HOST-SUFFIX,xboxlive.com
HOST-SUFFIX,xboxservices.com
HOST-SUFFIX,yammer.com
HOST-SUFFIX,yammerusercontent.com
IP-ASN,211157,no-resolve
IP-ASN,44907,no-resolve
IP-ASN,59930,no-resolve
IP-ASN,62014,no-resolve
IP-ASN,62041,no-resolve
PROCESS-NAME,LookupViewService
USER-AGENT,AppleNews*
USER-AGENT,AppleTV*
USER-AGENT,com.apple.news*
USER-AGENT,com.apple.trustd*
USER-AGENT,com.apple.tv*
