# https://raw.githubusercontent.com/ElementRef/AboutConfig/main/filter/element.ref.global.escapes.ini
HOST-SUFFIX,azurehdinsight.cn
HOST-SUFFIX,browserleaks.com
HOST-SUFFIX,ipleak.net
HOST-SUFFIX,opensourceinsight.dev
HOST-SUFFIX,opensourceinsights.dev
HOST-SUFFIX,plus.codes
HOST,adsbypasser.github.io
HOST,en.mrproblogger.com
HOST,mobileproxy.space
