# https://raw.githubusercontent.com/ElementRef/AboutConfig/main/filter/element.ref.direct.escapes.ini
HOST-SUFFIX,a1.mzstatic.com
HOST-SUFFIX,byteimg.com
HOST-SUFFIX,juejin.cn
HOST-SUFFIX,juejin.im
HOST-SUFFIX,lizhi.shop
HOST-SUFFIX,s.weibo.com
HOST,kelee.one
HOST,log.mmstat.com
HOST,loon.103516.xyz
HOST,sycm.mmstat.com
HOST,tva1.sinaimg.cn
# https://raw.githubusercontent.com/ishowshu/qx/main/rewrite/soul.snippet
IP-CIDR,13.127.149.196/32,no-resolve
IP-CIDR,52.194.158.59/32,no-resolve
IP-CIDR,47.56.131.76/32,no-resolve
IP-CIDR,47.75.72.47/32,no-resolve
IP-CIDR,3.0.163.78/32,no-resolve
