# https://raw.githubusercontent.com/ElementRef/AboutConfig/main/filter/element.ref.ai.custom.ini
HOST-SUFFIX,claude.ai
HOST-SUFFIX,claudeusercontent.com
HOST-SUFFIX,diabrowser.com
HOST-SUFFIX,diabrowser.engineering
# https://www.nodeseek.com/post-515952-1
HOST-SUFFIX,antigravity-unleash.goog
HOST-SUFFIX,optimizationguide-pa.googleapis.com
HOST-SUFFIX,us-central1.run.app
