# https://raw.githubusercontent.com/ElementRef/AboutConfig/main/filter/element.ref.global.escapes.ini
HOST-KEYWORD,www-cdn.
HOST-SUFFIX,azurehdinsight.cn
HOST-SUFFIX,blog.google
HOST-SUFFIX,blogger.com
HOST-SUFFIX,browserleaks.com
HOST-SUFFIX,googleusercontent.com
HOST-SUFFIX,ipleak.net
HOST-SUFFIX,mac-stats.com
HOST-SUFFIX,opensourceinsight.dev
HOST-SUFFIX,opensourceinsights.dev
HOST-SUFFIX,plus.codes
HOST,adsbypasser.github.io
HOST,alt1-mtalk.google.com
HOST,alt2-mtalk.google.com
HOST,alt3-mtalk.google.com
HOST,alt4-mtalk.google.com
HOST,alt5-mtalk.google.com
HOST,alt6-mtalk.google.com
HOST,alt7-mtalk.google.com
HOST,alt8-mtalk.google.com
HOST,dl.google.com
HOST,dl.l.google.com
HOST,en.mrproblogger.com
HOST,mobileproxy.space
HOST,mtalk.google.com
HOST,productionresultssa8.blob.core.windows.net
HOST,track.gumroad.com
HOST,update.googleapis.com
