# https://raw.githubusercontent.com/ElementRef/AboutConfig/main/filter/element.ref.direct.escapes.ini
HOST-SUFFIX,a1.mzstatic.com
HOST-SUFFIX,byteimg.com
HOST-SUFFIX,juejin.cn
HOST-SUFFIX,juejin.im
HOST-SUFFIX,lizhi.shop
HOST-SUFFIX,s.weibo.com
