# https://github.com/NSRingo/WeatherKit/releases/latest/download/iRingo.WeatherKit.snippet
hostname=weatherkit.apple.com
^https?:\/\/weatherkit\.apple\.com\/api\/v1\/availability\/ url script-response-body https://github-public-raw.spicicomic.workers.dev/ElementRef/AboutConfig/main/script/i.ringo.weather.kit.response.js?raw
^https?:\/\/weatherkit\.apple\.com\/api\/v2\/weather\/ url script-response-body https://github-public-raw.spicicomic.workers.dev/ElementRef/AboutConfig/main/script/i.ringo.weather.kit.response.js?raw
