# https://raw.githubusercontent.com/ishowshu/qx/main/rewrite/soul.snippet
hostname=ssp.soulapp.cn,increase-openapi.soulapp.cn,data-collector.soulapp.cn,post.soulapp.cn,api-account.soulapp.cn,api-a.soulapp.cn,gateway-mobile-gray.soulapp.cn,api-user.soulapp.cn,chat-live.soulapp.cn,api-chat.soulapp.cn,47.98.137.249,47.110.187.87
^https:\/\/ssp\.soulapp\.cn\/api\/q url reject-dict
^https:\/\/post\.soulapp\.cn\/v1\/post\/homepage\/ai\/assistant\/guide url reject-dict
^https:\/\/post\.soulapp\.cn\/v\d\/post\/homepage\/guide\/card url reject-dict
^https:\/\/post\.soulapp\.cn\/post\/relationUser\/chatRooms url reject-dict
^https:\/\/post\.soulapp\.cn\/homepage\/tabs\/v2 url script-response-body https://github-public-raw.spicicomic.workers.dev/ElementRef/AboutConfig/main/script/ishowshu.soul.js?raw
^https:\/\/increase-openapi\.soulapp\.cn\/increase\/fission\/getHomePageRedIcon url reject
^https:\/\/increase-openapi\.soulapp\.cn\/increase\/dusting\/getAddressBookDustings url reject-dict
^https:\/\/data-collector\.soulapp\.cn\/api\/data\/report\/v2 url reject-dict
^https:\/\/chat-live\.soulapp\.cn\/square\/relation\/guideUserList url script-response-body https://github-public-raw.spicicomic.workers.dev/ElementRef/AboutConfig/main/script/ishowshu.soul.js?raw
^https:\/\/chat-live\.soulapp\.cn\/live\/queryRelevantList url reject-dict
^https:\/\/chat-live\.soulapp\.cn\/live\/config\/rec-feedback url reject-dict
^https:\/\/chat-live\.soulapp\.cn\/chatroom\/getRoomTagInfo url script-response-body https://github-public-raw.spicicomic.workers.dev/ElementRef/AboutConfig/main/script/ishowshu.soul.js?raw
^https:\/\/chat-live\.soulapp\.cn\/chatroom\/chatClassifyRoomList url script-response-body https://github-public-raw.spicicomic.workers.dev/ElementRef/AboutConfig/main/script/ishowshu.soul.js?raw
^https:\/\/api-user\.soulapp\.cn\/v6\/planet\/config url script-response-body https://github-public-raw.spicicomic.workers.dev/ElementRef/AboutConfig/main/script/ishowshu.soul.js?raw
^https:\/\/api-user\.soulapp\.cn\/user\/matchRelation\/getChatCard url reject
^https:\/\/api-user\.soulapp\.cn\/user\/homepage\/metrics url script-response-body https://github-public-raw.spicicomic.workers.dev/ElementRef/AboutConfig/main/script/ishowshu.soul.js?raw
^https:\/\/api-user\.soulapp\.cn\/user\/desc\/getUserPersonalDesc url reject-dict
^https:\/\/api-user\.soulapp\.cn\/furion\/position\/content url reject-dict
^https:\/\/api-chat\.soulapp\.cn\/snapchat\/url url script-response-body https://github-public-raw.spicicomic.workers.dev/ElementRef/AboutConfig/main/script/ishowshu.soul.js?raw
^https:\/\/api-chat\.soulapp\.cn\/similar\/post\/intersect\/trigger url reject
^https:\/\/api-chat\.soulapp\.cn\/chat\/session\/quickButtonCheck url reject-dict
^https:\/\/api-chat\.soulapp\.cn\/chat\/quick\/menu url reject
^https:\/\/api-chat\.soulapp\.cn\/chat\/limitInfo url script-response-body https://github-public-raw.spicicomic.workers.dev/ElementRef/AboutConfig/main/script/ishowshu.soul.js?raw
^https:\/\/api-chat\.soulapp\.cn\/chat\/interact\/getEmojiList url reject
^https:\/\/api-chat\.soulapp\.cn\/chat\/guide\/defaultWord url reject
^https:\/\/api-chat\.soulapp\.cn\/chat\/entrance\/first url reject
^https:\/\/api-chat\.soulapp\.cn\/chat\/emoji\/recommend url reject
^https:\/\/api-chat\.soulapp\.cn\/addressBook\/showBubblingEnter url reject
^https:\/\/api-account\.soulapp\.cn\/teenager\/config url reject-dict
^https:\/\/api-a\.soulapp\.cn\/shara\/app\/url url reject
^https:\/\/api-a\.soulapp\.cn\/official\/scene\/module url reject-dict
^https:\/\/47\.110\.187\.87\/winterfell\/(?:v2\/)?getIpByDomain url reject-dict
