# https://raw.githubusercontent.com/NobyDa/Script/master/QuantumultX/Snippet/GoogleCAPTCHA.snippet
hostname=www.google.com*
^https:\/\/www\.google\.com(?:\.[a-z]+|)\/(?:search\?(?:|.+?&)q=|$) url script-response-body https://github-public-raw.spicicomic.workers.dev/ElementRef/AboutConfig/main/script/nobyda.google.captcha.js?raw
