# https://raw.githubusercontent.com/S7venYoung/QuantumultX/master/IThome_remove_ads_qx.conf
hostname=napi.ithome.com,dat.ruanmei.com
^https?:\/\/dat\.ruanmei\.com\/ithome\/money\/acd\.json$ url reject
^https:\/\/napi\.ithome\.com\/api\/(news\/indexv2\/iphone\/\d+|topmenu\/getfeeds\?) url script-response-body https://github-public-raw.spicicomic.workers.dev/ElementRef/AboutConfig/main/script/s7ven.young.it.home.js?raw
