# https://raw.githubusercontent.com/sub-store-org/Sub-Store/master/config/QX.snippet
hostname=sub.store
^https?:\/\/sub\.store\/((download)|api\/(preview|sync|(utils\/node-info))) url script-analyze-echo-response https://github-public-raw.spicicomic.workers.dev/ElementRef/AboutConfig/main/script/sub.store.org.1.js?raw
^https?:\/\/sub\.store url script-analyze-echo-response https://github-public-raw.spicicomic.workers.dev/ElementRef/AboutConfig/main/script/sub.store.org.0.js?raw
