name: Purge Some Config on jsDelivr Cache...

on:
  workflow_dispatch:

  schedule:
    - cron: '30 21 * * *'

jobs:
  build-deploy:
    runs-on: macos-latest
    steps:
      - name: Purge jsDelivr Cache
        uses: gacts/purge-jsdelivr-cache@v1
        with:
          url: |
            https://cdn.jsdelivr.net/gh/ripaojiedian/freenode@main/sub?raw
