name: Purge Some Config on jsDelivr Cache...

on:
  workflow_dispatch:

  schedule:
    - cron: '30 21 * * *'

jobs:
  build-deploy:
    runs-on: macos-latest
    steps:
      - name: Purge jsDelivr Cache
        uses: gacts/purge-jsdelivr-cache@v1
        with:
          url: |
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/conf/quantumult.x.conf?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/conf/vscode.settings.json?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/filter/element.ref.apples.mixture.ini?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/filter/element.ref.direct.mixture.ini?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/filter/element.ref.global.mixture.ini?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/filter/element.ref.openai.mixture.ini?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/filter/element.ref.reject.mixture.ini?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/filter/element.ref.stream.mixture.ini?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/filter/element.ref.tiktok.mixture.ini?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/filter/element.ref.ublock.mixture.ini?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/rewrite/app2smile.qidian.conf?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/rewrite/app2smile.qq.news.conf?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/rewrite/app2smile.spotify.conf?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/rewrite/app2smile.tieba.conf?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/rewrite/bili.universe.adblock.conf?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/rewrite/bili.universe.enhanced.conf?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/rewrite/blackmatrix7.rewrite.conf?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/rewrite/ddgksf2013.amap.conf?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/rewrite/ddgksf2013.cai.niao.conf?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/rewrite/ddgksf2013.cai.yun.conf?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/rewrite/ddgksf2013.cloud.music.conf?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/rewrite/ddgksf2013.red.book.conf?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/rewrite/ddgksf2013.smzdm.conf?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/rewrite/ddgksf2013.startup.conf?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/rewrite/ddgksf2013.weibo.conf?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/rewrite/ddgksf2013.ximalaya.conf?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/rewrite/ddgksf2013.zhihu.conf?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/rewrite/maasea.youtube.conf?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/rewrite/nobyda.google.captcha.conf?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/rewrite/sub.store.org.conf?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/rewrite/virgil.clyne.httpdns.block.conf?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/rewrite/zenmo.fei.shi.didi.conf?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/rewrite/zirawell.ddxq.conf?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/rewrite/zzpiglet.wechat.110.conf?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/app2smile.baidu.map.js?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/app2smile.qidian.js?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/app2smile.qq.news.js?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/app2smile.spotify.header.js?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/app2smile.spotify.json.js?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/app2smile.spotify.proto.js?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/app2smile.tieba.json.js?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/app2smile.tieba.proto.js?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/bili.universe.adblock.request.js?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/bili.universe.adblock.response.js?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/bili.universe.enhanced.response.js?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.amap.js?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.amdc.js?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.cai.niao.js?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.cai.yun.js?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.cloud.music.js?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.red.book.js?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.server.info.pure.js?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.smzdm.json.js?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.startup.12306.js?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.startup.123pan.js?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.startup.555.js?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.startup.abchina.js?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.startup.ahfs.js?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.startup.baishi.tv.js?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.startup.caixin.js?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.startup.coolapk.js?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.startup.dict.js?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.startup.dong.qiu.di.js?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.startup.fly.js?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.startup.hang.lv.zong.heng.js?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.startup.iqiyi.js?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.startup.ithome.js?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.startup.jd.js?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.startup.jingxi.js?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.startup.ping.an.js?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.startup.pupu.market.js?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.startup.qidian.js?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.startup.quark.js?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.startup.sf.js?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.startup.stay.js?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.startup.zhihu.js?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.weibo.js?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.ximalaya.js?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.zhihu.js?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/kop.xiao.ip.api.js?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/kop.xiao.resource.parser.js?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/kop.xiao.streaming.ui.check.js?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/maasea.youtube.response.js?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/nobyda.google.captcha.js?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/sub.store.org.0.js?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/sub.store.org.1.js?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/sub.store.org.cron.sync.artifacts.js?raw
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/zzpiglet.wechat.110.js?raw
            https://cdn.jsdelivr.net/gh/ripaojiedian/freenode@main/sub?raw
