name: Purge Some Config on jsDelivr Cache...

on:
  workflow_dispatch:

  schedule:
    - cron: '30 21 * * *'

jobs:
  build-deploy:
    runs-on: macos-latest
    steps:
      - name: Purge jsDelivr Cache
        uses: gacts/purge-jsdelivr-cache@v1
        with:
          url: |
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/conf/quantumult.x.conf
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/conf/vscode.settings.json
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/filter/element.ref.apples.mixture.ini
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/filter/element.ref.direct.mixture.ini
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/filter/element.ref.global.mixture.ini
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/filter/element.ref.openai.mixture.ini
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/filter/element.ref.reject.mixture.ini
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/filter/element.ref.stream.mixture.ini
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/filter/element.ref.tiktok.mixture.ini
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/filter/element.ref.ublock.mixture.ini
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/rewrite/app2smile.qidian.conf
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/rewrite/app2smile.qq.news.conf
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/rewrite/app2smile.spotify.conf
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/rewrite/app2smile.tieba.conf
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/rewrite/bili.universe.adblock.conf
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/rewrite/bili.universe.enhanced.conf
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/rewrite/blackmatrix7.rewrite.conf
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/rewrite/ddgksf2013.amap.conf
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/rewrite/ddgksf2013.cai.niao.conf
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/rewrite/ddgksf2013.cai.yun.conf
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/rewrite/ddgksf2013.cloud.music.conf
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/rewrite/ddgksf2013.red.book.conf
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/rewrite/ddgksf2013.smzdm.conf
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/rewrite/ddgksf2013.startup.conf
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/rewrite/ddgksf2013.weibo.conf
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/rewrite/ddgksf2013.ximalaya.conf
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/rewrite/ddgksf2013.zhihu.conf
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/rewrite/maasea.youtube.conf
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/rewrite/virgil.clyne.httpdns.block.conf
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/rewrite/zirawell.ddxq.conf
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/rewrite/zzpiglet.wechat.110.conf
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/app2smile.baidu.map.js
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/app2smile.qidian.js
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/app2smile.qq.news.js
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/app2smile.spotify.header.js
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/app2smile.spotify.json.js
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/app2smile.spotify.proto.js
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/app2smile.tieba.json.js
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/app2smile.tieba.proto.js
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/bili.universe.adblock.request.js
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/bili.universe.adblock.response.js
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/bili.universe.enhanced.response.js
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.amap.js
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.amdc.js
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.cai.niao.js
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.cai.yun.js
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.cloud.music.js
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.red.book.js
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.server.info.pure.js
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.smzdm.json.js
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.startup.12306.js
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.startup.123pan.js
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.startup.555.js
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.startup.abchina.js
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.startup.ahfs.js
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.startup.baishi.tv.js
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.startup.caixin.js
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.startup.coolapk.js
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.startup.dict.js
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.startup.dong.qiu.di.js
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.startup.fly.js
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.startup.hang.lv.zong.heng.js
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.startup.iqiyi.js
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.startup.ithome.js
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.startup.jd.js
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.startup.jingxi.js
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.startup.ping.an.js
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.startup.pupu.market.js
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.startup.qidian.js
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.startup.quark.js
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.startup.sf.js
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.startup.stay.js
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.startup.zhihu.js
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.weibo.js
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.ximalaya.js
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/ddgksf2013.zhihu.js
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/kop.xiao.ip.api.js
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/kop.xiao.resource.parser.js
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/kop.xiao.streaming.ui.check.js
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/maasea.youtube.response.js
            https://cdn.jsdelivr.net/gh/ElementRef/AboutConfig@main/script/zzpiglet.wechat.110.js
            https://cdn.jsdelivr.net/gh/ripaojiedian/freenode@main/sub
